using System;
using System.Collections.Generic;

namespace Mastermind
{
    class ConsoleHelper
    {
        /// <summary>
        /// Displays the main menu for the user to choose an option from
        /// </summary>
        /// <returns>A number indicating which menu item the user chose</returns>
        public int MenuSelect()
        {
            Console.WriteLine($"Welcome to Mastermind! {Environment.NewLine}");
            Console.WriteLine($"Please select an option: {Environment.NewLine}" +
            $"1.) Play Game {Environment.NewLine}" +
            $"2.) View Rules{Environment.NewLine}" +
            $"3.) Options {Environment.NewLine}" +
            $"4.) Exit {Environment.NewLine}");
            return IntegerSelector(1, 4);
        }
        /// <summary>
        /// explains the rules of the game on the console
        /// </summary>
        public void DisplayRules(InitialConditions gameRules)
        {
            Console.WriteLine($"The following rules are for {gameRules.Difficulty} difficulty.");
            Console.WriteLine($"The object of the game is to guess the hidden pattern generated by the computer. Once the randomly generated pattern is correctly guessed, the player wins! {Environment.NewLine}" +
            $"1.) The player gets {gameRules.MaxGuesses} guesses to correctly guess the hidden pattern. {Environment.NewLine}" +
            $"2.) The pattern is {gameRules.PatternLength} numbers long. {Environment.NewLine}" +
            $"3.) Each of the numbers are between {gameRules.PatternMinimum} and {gameRules.PatternMax} inclusive.{Environment.NewLine}" +
            $"4.) When the player guesses the correct number in the incorrect place, the game will show a \"-\".{Environment.NewLine}" +
            $"5.) When the player guesses the correct number in the correct place, the game will show a \"+\".{Environment.NewLine}" +
            $"6.) When the player types anything but numbers that are between {gameRules.PatternMinimum} and {gameRules.PatternMax}, the game will not recognize the character and the guess will be wasted.{Environment.NewLine}" +
            $"7.) The pattern can repeat numbers. {Environment.NewLine}" +
            $"8.) When the player repeats a number, both are counted as independent numbers (see below).{Environment.NewLine}{Environment.NewLine}" +
            $"For example, pretend the answer is:{Environment.NewLine}{Environment.NewLine}" +
            $"2 3 4 5{Environment.NewLine}{Environment.NewLine}" +
            $"and the player guesses:{Environment.NewLine}{Environment.NewLine}" +
            $"1234{Environment.NewLine}{Environment.NewLine}" +
            $"the computer will respond with:{Environment.NewLine}{Environment.NewLine}" +
            $"1.) 1 2 3 4 ---{Environment.NewLine}{Environment.NewLine}" +
            $"because the correct numbers 2, 3, and 4 were guessed in the incorrect spots.{Environment.NewLine}" +
            $"If the player were to guess{Environment.NewLine}{Environment.NewLine}" +
            $"3333{Environment.NewLine}{Environment.NewLine}" +
            $"The computer would respond with:{Environment.NewLine}{Environment.NewLine}" +
            $"1.) 1 2 3 4 ---{Environment.NewLine}" +
            $"2.) 3 3 3 3 +---{Environment.NewLine}{Environment.NewLine}" +
            $"since 3 is in the answer. Despite 3 being in the answer only once, the game will recognize that each individual 3 is in the answer, only in incorrect positions{Environment.NewLine}" +
            $"If the player were to then guess{Environment.NewLine}{Environment.NewLine}" +
            $"23g5{Environment.NewLine}{Environment.NewLine}" +
            $"the computer will respond with:{Environment.NewLine}{Environment.NewLine}" +
            $"1.) 1 2 3 4 ---{Environment.NewLine}" +
            $"2.) 3 3 3 3 +---{Environment.NewLine}" +
            $"3.) 2 3 g 5 +++{Environment.NewLine}{Environment.NewLine}" +
            $"since 2, 3, and 5 are correct answers in the currect positions. g is ignored");
            Console.WriteLine("(press enter to return to the main menu)");
            Console.ReadLine();
        }
        /// <summary>
        /// Displays a screen that prompts the user for a number. TryParses until user returns a valid number.
        /// </summary>
        /// <returns>Returns an integer selected by the user</returns>
        public int IntegerSelector()
        {
            string selector;
            bool isValid;
            do
            {
                Console.Write($"Please type an integer: ");
                selector = Console.ReadLine();
                isValid = int.TryParse(selector, out int i);
                if (!isValid)
                {
                    Console.WriteLine("Please enter a valid integer");
                }
            } while (!isValid);
            int selected = int.Parse(selector);
            return selected;
        }
        /// <summary>
        /// Displays a screen that prompts the user for a number between two numbers (min and max). TryParses until user returns a valid number.
        /// </summary>
        /// <param name="min">The maximum value accepted (inclusive)</param>
        /// <param name="max">The minimum value accepted (inclusive)</param>
        /// <returns>an integer between min and max (inclusive)</returns>
        public int IntegerSelector(int min, int max)
        {
            int selector = IntegerSelector();
            bool isValid;
            do
            {
                isValid = selector >= min && selector <= max;
                if (!isValid)
                {
                    Console.WriteLine($"Please enter a valid integer between {min} and {max}");
                    selector = IntegerSelector();
                }
            } while (!isValid);
            return selector;
        }
        /// <summary>
        /// Prompts the user for the difficulty they would like to select
        /// </summary>
        public int DifficultySelector()
        {
            Console.WriteLine($"Please select an option: {Environment.NewLine}" +
            $"1.) Easy{Environment.NewLine}" +
            $"2.) Medium{Environment.NewLine}" +
            $"3.) Hard{Environment.NewLine}" +
            $"4.) Very Hard{Environment.NewLine}");
            return IntegerSelector(1, 4);
        }
        /// <summary>
        /// Gets a valid guess from the user. If the user inputs something other than a valid integer, it penelizes the user by invalidating their guess.
        /// </summary>
        /// <param name="numberOfColumns">Length of the guess in characters</param>
        /// <returns>a list of the guess</returns>
        public List<int> GetPlayerGuess(InitialConditions Rules)
        {
            string exampleInt = GetExampleIntFromRules(Rules);
            string guessString;
            List<int> guess = new List<int>();
            bool validGuess;
            do
            {
                guessString = Console.ReadLine();
                validGuess = guessString.Length == Rules.PatternLength;
                if (!validGuess)
                {
                    Console.WriteLine($"That is not a valid guess because you do not have a valid number of integers {Environment.NewLine}" +
                        $"Please enter {Rules.PatternLength} numbers (without space, I.E. {exampleInt})");
                }
            } while (!validGuess);
            foreach (char c in guessString)
            {
                string s = $"{c}";
                if (!int.TryParse(s, out int i))
                {
                    guess.Add(int.MinValue);
                }
                else
                {
                    guess.Add(int.Parse(s));
                }
            }
            return guess;
        }
        /// <summary>
        /// A helper method that prints an character a few times in a row
        /// </summary>
        /// <param name="amountOfTimesToRepeat">how many times the character should be repeated</param>
        /// <param name="phrase">the character or phrase to be repeated</param>
        /// <param name="newLine">if there should be a carriage return after the method finishes</param>
        public void RepeatPrint(int amountOfTimesToRepeat, string phrase, bool newLine = true)
        {
            for (int i = 0; i < amountOfTimesToRepeat; i++)
            {
                Console.Write(phrase);
            }
            if (newLine)
            {
                Console.WriteLine();
            }
        }
        /// <summary>
        /// A helper method that prints the previous guesses and their quality
        /// </summary>
        public void PrintPreviousGuesses(List<Guess> guessList)
        {
            int i = 1;
            foreach(Guess guess in guessList)
            {
                Console.Write($"{i}.) {guess.ToString()}");
                RepeatPrint(guess.AbsoluteCorrect, " +", false);
                RepeatPrint(guess.MarginalCorrect, " -");
                i++;
            }
        }
        /// <summary>
        /// Displays the win or loss screen
        /// </summary>
        /// <param name="win">if the player won or lost</param>
        /// <param name="correctAnswer">The correct answer</param>
        public void WinLoss(bool win, List<int> correctAnswer)
        {
            if (win)
            {
                Console.WriteLine("Congratulations, You Have Won!");
                Console.WriteLine();
                Console.WriteLine(@"       .''.      .        *''*    :_\/_:     .
      :_\/_:   _\(/_  .:.*_\/_*   : /\ :  .'.:.'.
  .''.: /\ :    /)\   ':'* /\ *  : '..'.  -=:o:=-
 :_\/_:'.:::.  | ' *''*    * '.\'/.'_\(/_ '.':'.'
 : /\ : :::::  =  *_\/_*     -= o =- /)\     '  *
  '..'  ':::' === * /\ *     .'/.\'.  ' ._____
      *        |   *..*         :       |.   |' .---"" |
        *      | _.--'|  ||   | _|    |
        *      |  .- '|       __  |   |  |    ||      |
     .---- -.   |  | ' |  ||  |  | |   |  |    ||      |
 ___'       ' / ""\ |  '-."".    '-'   '-.'    '`      |____
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   ~-~-~-~-~-~-~-~-~-~   /|
        )        ~-~-~-~-~-~-~-~  /|~       /_|\
      _-H-__    -~-~-~-~-~-~     /_|\    -~======-~
~-\XXXXXXXXXX/~     ~-~-~-~     /__|_\ ~-~-~-~
~-~-~-~-~-~    ~-~~-~-~-~-~    ========  ~-~-~-~
      ~-~~-~-~-~-~-~-~-~-~-~-~-~ ~-~~-~-~-~-~
                        ~-~~-~-~-~-~");
            }
            else
            {
                Console.WriteLine("You Lost");
                Console.Write($"The correct answer was ");
                foreach(int i in correctAnswer)
                {
                    Console.Write($"{i} ");
                }
                Console.WriteLine();
            }
            Console.WriteLine("Press enter to continue");
            Console.ReadLine();
        }
        /// <summary>
        /// Prints the header for the game from the given rules
        /// </summary>
        /// <param name="Rules">The rules of the particular game</param>
        public void PrintGuessHeader(InitialConditions Rules)
        {
            string exampleInt = GetExampleIntFromRules(Rules);
            Console.Clear();
            RepeatPrint(Rules.PatternLength, "? ");
            Console.WriteLine($"Please enter {Rules.PatternLength} numbers between {Rules.PatternMinimum} and {Rules.PatternMax} {Environment.NewLine}" +
            $"I.E. {exampleInt}");
            Console.WriteLine();
        }
        /// <summary>
        /// Takes in the rules of the game and returns a string of an example input. IE, if the PatternLength is 4, will return 1234
        /// </summary>
        /// <param name="Rules">The rules of the particular game</param>
        /// <returns>A string of an example answer from the given rules</returns>
        public string GetExampleIntFromRules(InitialConditions Rules)
        {
            string exampleInt = "";

            for (int i = 1; i <= Rules.PatternLength; i++)
            {
                int num = i;
                while (num > Rules.PatternMax)
                {
                    num -= Rules.PatternMax;
                }
                exampleInt += $"{num}";

            }
            return exampleInt;
        }
    }
}
